In [1]:
import numpy as np
import pandas as pd

In [17]:
A = np.array([[1,12], [13,4], [5,6]])
A

array([[ 1, 12],
       [13,  4],
       [ 5,  6]])

In [18]:
m = np.mean(A, axis=0)
m

array([6.33333333, 7.33333333])

In [19]:
scaled = A - m
scaled

array([[-5.33333333,  4.66666667],
       [ 6.66666667, -3.33333333],
       [-1.33333333, -1.33333333]])

In [20]:
c = np.cov(scaled.T)
c

array([[ 37.33333333, -22.66666667],
       [-22.66666667,  17.33333333]])

In [21]:
eigval, eigvec = np.linalg.eig(c)

In [22]:
eigval

array([52.10787223,  2.55879443])

In [23]:
eigvec

array([[ 0.83774704,  0.54605851],
       [-0.54605851,  0.83774704]])

In [24]:
pc = eigvec.T.dot(scaled.T)
pc.T

array([[-7.01625726,  0.99717413],
       [ 7.4051753 ,  0.84789994],
       [-0.38891804, -1.84507407]])