In [1]:
import numpy as np

## Basics of Numpy

In [2]:
range(0 ,10)

range(0, 10)

In [3]:
type(range(0, 10))

range

In [5]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Note: We can use range and then wrap it using np.array to create an array object np.array(range(0, 10)) or directly call the np.arange(0, 10)

In [8]:
np.linspace(0, 6, 7)

array([0., 1., 2., 3., 4., 5., 6.])

In [9]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [10]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(shape=(2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(start=0, stop=29, num=30).reshape(3, 10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [15]:
np.linspace(start=-3, stop=3, retstep=True, num=60)

(array([-3.        , -2.89830508, -2.79661017, -2.69491525, -2.59322034,
        -2.49152542, -2.38983051, -2.28813559, -2.18644068, -2.08474576,
        -1.98305085, -1.88135593, -1.77966102, -1.6779661 , -1.57627119,
        -1.47457627, -1.37288136, -1.27118644, -1.16949153, -1.06779661,
        -0.96610169, -0.86440678, -0.76271186, -0.66101695, -0.55932203,
        -0.45762712, -0.3559322 , -0.25423729, -0.15254237, -0.05084746,
         0.05084746,  0.15254237,  0.25423729,  0.3559322 ,  0.45762712,
         0.55932203,  0.66101695,  0.76271186,  0.86440678,  0.96610169,
         1.06779661,  1.16949153,  1.27118644,  1.37288136,  1.47457627,
         1.57627119,  1.6779661 ,  1.77966102,  1.88135593,  1.98305085,
         2.08474576,  2.18644068,  2.28813559,  2.38983051,  2.49152542,
         2.59322034,  2.69491525,  2.79661017,  2.89830508,  3.        ]),
 0.1016949152542373)

In [9]:
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
np.arange(0, 15).reshape(3, 5)[1][3]

8

In [7]:
np.arange(0, 15).reshape(3, 5)[1, 3]

8

In [8]:
np.arange(0, 15).reshape(3, 5)[0:3, 1:2]

array([[ 1],
       [ 6],
       [11]])

In [10]:
arry = np.arange(0, 15).reshape(3, 5)
arry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arry[arry >= 4]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Call by reference

In [17]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = a[:5]
b

array([0, 1, 2, 3, 4])

In [19]:
b[:] = 0
b

array([0, 0, 0, 0, 0])

In [20]:
a

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

In [21]:
c = a.copy(order='C')
c

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

In [23]:
c[:5] = 10
c

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [24]:
a

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])