In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0-dev20210604'

##### Constant

In [3]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10, 7], 
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
my_tensor = tf.constant([[[1, 2, 3],
                         [4, 5, 6]],
                        [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                        [16, 17, 18]]], dtype=tf.int16)
my_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int16)>

In [12]:
my_tensor.ndim

3

##### Variable

In [13]:
change_tensor = tf.Variable([10, 7])
unchange_tensor = tf.constant([10, 7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
change_tensor[0] = 7
change_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
change_tensor[0].assign(7)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
unchange_tensor[0] = 7
unchange_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [17]:
unchange_tensor[0].assign[7]
unchange_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

##### Random Tensors

In [18]:
rand_1 = tf.random.Generator.from_seed(42)

In [19]:
rand_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
rand_1.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7647915 , 0.03845465],
       [0.8506975 , 0.20781887],
       [0.711869  , 0.8843919 ]], dtype=float32)>

In [21]:
rand_1.normal(shape=(3,2)) == rand_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [22]:
rand_1 = tf.random.Generator.from_seed(3)
rand_1.normal(shape=(3,2)) == rand_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [23]:
rand_1.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8398994 , 0.92632127],
       [0.10943472, 0.00302172],
       [0.19150412, 0.04563546]], dtype=float32)>

In [24]:
rand_1.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.28062475, 0.50312376],
       [0.9028803 , 0.17021883],
       [0.1053102 , 0.04724419]], dtype=float32)>

##### Shuffle

- Randomly shuffles a tensor along its first dimension.

In [25]:
import numpy as np

In [29]:
not_shuffle = tf.constant(np.random.randint(10, size=(3, 2)))
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [3, 0],
       [9, 3]])>

In [31]:
print(tf.random.shuffle(not_shuffle), tf.random.shuffle(not_shuffle))

tf.Tensor(
[[3 0]
 [3 4]
 [9 3]], shape=(3, 2), dtype=int32) tf.Tensor(
[[3 0]
 [9 3]
 [3 4]], shape=(3, 2), dtype=int32)


In [36]:
tf.ones(shape=(5, 3), name='tf_ones')

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [42]:
tf.constant(np.arange(1, 25), shape=(2, 2, 3, 2), dtype=np.int32)

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]])>

In [51]:
print(f'''
Matrix: \n{np.random.randint(10, size=(3, 2, 4, 5))}, 
Rank of a matrix: {np.random.randint(10, size=(3, 2, 4, 5)).ndim}, 
Size of matrix: {np.random.randint(10, size=(3, 2, 4, 5)).size}''')


Matrix: 
[[[[0 2 5 4 4]
   [3 1 7 5 7]
   [6 9 4 9 4]
   [4 4 5 3 5]]

  [[7 6 8 8 7]
   [0 6 5 4 3]
   [7 1 5 1 0]
   [7 1 2 0 4]]]


 [[[4 3 5 8 6]
   [8 6 0 1 7]
   [4 3 8 5 6]
   [3 3 7 1 4]]

  [[4 5 9 1 1]
   [4 5 1 0 8]
   [0 2 1 0 2]
   [1 0 3 2 7]]]


 [[[4 8 5 5 9]
   [7 2 0 7 7]
   [1 6 9 1 1]
   [4 0 0 4 5]]

  [[3 4 9 7 0]
   [3 1 2 7 4]
   [3 5 2 7 8]
   [3 4 1 1 7]]]], 
Rank of a matrix: 4, 
Size of matrix: 120


In [66]:
my_matrix = tf.constant(np.random.randint(10, size=(3, 2, 3, 2)))
my_matrix

<tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[4, 0],
         [2, 7],
         [1, 7]],

        [[5, 0],
         [0, 2],
         [5, 9]]],


       [[[8, 0],
         [6, 8],
         [4, 6]],

        [[0, 0],
         [0, 4],
         [0, 0]]],


       [[[8, 9],
         [9, 9],
         [4, 0]],

        [[8, 1],
         [8, 9],
         [1, 8]]]])>

In [69]:
print(f'''
Matrix: \n{my_matrix}, 
Rank of a matrix: {my_matrix.ndim}, 
Size of matrix: {tf.size(my_matrix)},
Shape: {my_matrix.shape}
Shape at 0 index: {my_matrix.shape[0]}
Shape at last dimension: {my_matrix.shape[-1]},
Size: {tf.size(my_matrix).numpy()}''')


Matrix: 
[[[[4 0]
   [2 7]
   [1 7]]

  [[5 0]
   [0 2]
   [5 9]]]


 [[[8 0]
   [6 8]
   [4 6]]

  [[0 0]
   [0 4]
   [0 0]]]


 [[[8 9]
   [9 9]
   [4 0]]

  [[8 1]
   [8 9]
   [1 8]]]], 
Rank of a matrix: 4, 
Size of matrix: 36,
Shape: (3, 2, 3, 2)
Shape at 0 index: 3
Shape at last dimension: 2,
Size: 36


In [70]:
tf.size(my_matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [71]:
tf.size(my_matrix).numpy()

36

##### Indexing just like Python List

In [81]:
my_matrix = np.arange(120)
my_matrix = my_matrix.reshape((2,3,4,5))
my_matrix

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [82]:
print(f'''
First 2 elements of each dimension
{my_matrix[:2, :2, :2, :2]}''')


First 2 elements of each dimension
[[[[ 0  1]
   [ 5  6]]

  [[20 21]
   [25 26]]]


 [[[60 61]
   [65 66]]

  [[80 81]
   [85 86]]]]


In [83]:
print(f'''
Get the first element from each dimension expect for the last one
{my_matrix[:1, :1, :1, :]}''')


Get the first element from each dimension expect for the last one
[[[[0 1 2 3 4]]]]


In [86]:
print(f'''
Get the first element from each dimension expect for the third one
{my_matrix[:1, :1, :, :1]}''')


Get the first element from each dimension expect for the third one
[[[[ 0]
   [ 5]
   [10]
   [15]]]]


In [87]:
print(f'''
Get the first element from each dimension expect for the second one
{my_matrix[:1, :, :1, :1]}''')


Get the first element from each dimension expect for the second one
[[[[ 0]]

  [[20]]

  [[40]]]]


In [88]:
print(f'''
Get the first element from each dimension expect for the first one
{my_matrix[:, :1, :1, :1]}''')


Get the first element from each dimension expect for the first one
[[[[ 0]]]


 [[[60]]]]


##### Extra-dimension

In [92]:
my_matrix2 = tf.constant( np.random.randint(9, size=(2,3)))
my_matrix2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 3, 8],
       [8, 3, 8]])>

In [94]:
my_matrix2.shape, my_matrix2.ndim

(TensorShape([2, 3]), 2)

In [95]:
my_matrix3 = my_matrix2[..., tf.newaxis]
my_matrix3.shape, my_matrix3.ndim

(TensorShape([2, 3, 1]), 3)

In [96]:
my_matrix3

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[7],
        [3],
        [8]],

       [[8],
        [3],
        [8]]])>

In [97]:
my_matrix31 = tf.expand_dims(my_matrix2, axis=-1)
my_matrix31.shape, my_matrix31.ndim

(TensorShape([2, 3, 1]), 3)

In [98]:
my_matrix31

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[7],
        [3],
        [8]],

       [[8],
        [3],
        [8]]])>

In [99]:
tf.expand_dims(my_matrix2, axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[7, 3, 8],
        [8, 3, 8]]])>

In [100]:
tf.expand_dims(my_matrix2, axis=1)

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[7, 3, 8]],

       [[8, 3, 8]]])>

### Tensor Operations

In [106]:
my_matrix2 = tf.constant(np.random.randint(9, size=(2,3)))
print(f'''
{my_matrix2}
Adding 10
{my_matrix2+10}''')


[[3 8 6]
 [2 1 1]]
Adding 10
[[13 18 16]
 [12 11 11]]


In [107]:
print(f'''
{my_matrix2}
Multiply by 10
{my_matrix2*10}''')


[[3 8 6]
 [2 1 1]]
Adding 10
[[30 80 60]
 [20 10 10]]


In [112]:
print(f'''
{my_matrix2}
Multiplying 10
{tf.math.multiply(my_matrix2, 10) }''')


[[3 8 6]
 [2 1 1]]
Multiplying 10
[[30 80 60]
 [20 10 10]]


In [113]:
print(f'''
{my_matrix2}
Multiplying 10
{tf.math.add(my_matrix2, 10) }''')


[[3 8 6]
 [2 1 1]]
Multiplying 10
[[13 18 16]
 [12 11 11]]


##### Matrix multiplication

In [115]:
np.arange(1, 7).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.arange(7, 13).reshape(3, 2)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [119]:
np.dot(np.arange(1, 7).reshape(2, 3), np.arange(7, 13).reshape(3, 2))

array([[ 58,  64],
       [139, 154]])

In [120]:
tf.matmul(np.arange(1, 7).reshape(2, 3), np.arange(7, 13).reshape(3, 2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [123]:
tf.matmul( tf.transpose(np.arange(1, 7).reshape(2, 3)), tf.transpose(np.arange(7, 13).reshape(3, 2)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  49,  59],
       [ 54,  68,  82],
       [ 69,  87, 105]])>

##### Casting data

In [131]:
const_32 = tf.constant(np.arange(1, 7).reshape(3, 2), dtype=tf.int32)
const_32

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [132]:
tf.cast(const_32, dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

In [133]:
const_32 = tf.constant(np.arange(1, 7).reshape(3, 2), dtype=tf.float32)
const_32

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [134]:
tf.cast(const_32, dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

##### Aggregating Tensors

In [137]:
const_32, tf.reduce_min(const_32), tf.reduce_max(const_32), tf.reduce_mean(const_32)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.5>)

In [141]:
tf.reduce_prod(const_32), tf.reduce_sum(const_32)

(<tf.Tensor: shape=(), dtype=float32, numpy=720.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=21.0>)

In [143]:
tf.math.reduce_std(const_32), tf.math.reduce_variance(const_32)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.7078251>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.9166667>)

##### Positional Min and Max

In [148]:
matrix_54 = tf.random.uniform(shape=(5, 4))
matrix_54

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.3973397 , 0.424412  , 0.37168002, 0.375906  ],
       [0.3075881 , 0.2506727 , 0.82194746, 0.36208236],
       [0.80988574, 0.4883306 , 0.8095002 , 0.26410222],
       [0.9951496 , 0.471609  , 0.24197567, 0.8959322 ],
       [0.32610905, 0.38248146, 0.47827947, 0.27135372]], dtype=float32)>

In [149]:
tf.argmax(matrix_54)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 2, 1, 3], dtype=int64)>

In [154]:
tf.argmax(matrix_54, axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 2, 1, 3], dtype=int64)>

In [155]:
tf.argmax(matrix_54, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 0, 0, 2], dtype=int64)>

In [159]:
matrix_54[tf.argmax(matrix_54)]

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 2, 1, 3], dtype=int64)>

In [164]:
tf.argmin(matrix_54).numpy()

array([1, 1, 3, 2], dtype=int64)

In [162]:
matrix_54[tf.argmin(matrix_54).numpy()]

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got array([1, 1, 3, 2], dtype=int64)

In [174]:
matrix_squez = tf.constant(
    tf.random.uniform(shape=[50]), shape=(1, 1, 50, 1, 1, 1)
)
matrix_squez

<tf.Tensor: shape=(1, 1, 50, 1, 1, 1), dtype=float32, numpy=
array([[[[[[0.71128917]]],


         [[[0.77877116]]],


         [[[0.36490285]]],


         [[[0.9530003 ]]],


         [[[0.49915147]]],


         [[[0.31188822]]],


         [[[0.39449155]]],


         [[[0.5906935 ]]],


         [[[0.13221145]]],


         [[[0.37026978]]],


         [[[0.5638151 ]]],


         [[[0.9600681 ]]],


         [[[0.38443553]]],


         [[[0.22657108]]],


         [[[0.7337091 ]]],


         [[[0.18864179]]],


         [[[0.2322309 ]]],


         [[[0.52372944]]],


         [[[0.5088606 ]]],


         [[[0.8803636 ]]],


         [[[0.11377084]]],


         [[[0.6813196 ]]],


         [[[0.54288495]]],


         [[[0.04928088]]],


         [[[0.68769765]]],


         [[[0.31924403]]],


         [[[0.47953212]]],


         [[[0.22639894]]],


         [[[0.34083533]]],


         [[[0.36209035]]],


         [[[0.96956146]]],


         [[[0.6346265 ]]],


         [[

In [175]:
matrix_squez.ndim

6

In [176]:
tf.squeeze(matrix_squez)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.71128917, 0.77877116, 0.36490285, 0.9530003 , 0.49915147,
       0.31188822, 0.39449155, 0.5906935 , 0.13221145, 0.37026978,
       0.5638151 , 0.9600681 , 0.38443553, 0.22657108, 0.7337091 ,
       0.18864179, 0.2322309 , 0.52372944, 0.5088606 , 0.8803636 ,
       0.11377084, 0.6813196 , 0.54288495, 0.04928088, 0.68769765,
       0.31924403, 0.47953212, 0.22639894, 0.34083533, 0.36209035,
       0.96956146, 0.6346265 , 0.17654824, 0.35434842, 0.7780837 ,
       0.4478408 , 0.43103004, 0.73788166, 0.37174475, 0.71096385,
       0.91982245, 0.8890587 , 0.51341915, 0.51375294, 0.6079956 ,
       0.53363097, 0.30792522, 0.72625375, 0.4965216 , 0.9710821 ],
      dtype=float32)>

In [177]:
tf.squeeze(matrix_squez).ndim

1

In [178]:
tf.squeeze(matrix_squez, axis=0)

<tf.Tensor: shape=(1, 50, 1, 1, 1), dtype=float32, numpy=
array([[[[[0.71128917]]],


        [[[0.77877116]]],


        [[[0.36490285]]],


        [[[0.9530003 ]]],


        [[[0.49915147]]],


        [[[0.31188822]]],


        [[[0.39449155]]],


        [[[0.5906935 ]]],


        [[[0.13221145]]],


        [[[0.37026978]]],


        [[[0.5638151 ]]],


        [[[0.9600681 ]]],


        [[[0.38443553]]],


        [[[0.22657108]]],


        [[[0.7337091 ]]],


        [[[0.18864179]]],


        [[[0.2322309 ]]],


        [[[0.52372944]]],


        [[[0.5088606 ]]],


        [[[0.8803636 ]]],


        [[[0.11377084]]],


        [[[0.6813196 ]]],


        [[[0.54288495]]],


        [[[0.04928088]]],


        [[[0.68769765]]],


        [[[0.31924403]]],


        [[[0.47953212]]],


        [[[0.22639894]]],


        [[[0.34083533]]],


        [[[0.36209035]]],


        [[[0.96956146]]],


        [[[0.6346265 ]]],


        [[[0.17654824]]],


        [[[0.35434

In [180]:
tf.squeeze(matrix_squez, axis=3)

<tf.Tensor: shape=(1, 1, 50, 1, 1), dtype=float32, numpy=
array([[[[[0.71128917]],

         [[0.77877116]],

         [[0.36490285]],

         [[0.9530003 ]],

         [[0.49915147]],

         [[0.31188822]],

         [[0.39449155]],

         [[0.5906935 ]],

         [[0.13221145]],

         [[0.37026978]],

         [[0.5638151 ]],

         [[0.9600681 ]],

         [[0.38443553]],

         [[0.22657108]],

         [[0.7337091 ]],

         [[0.18864179]],

         [[0.2322309 ]],

         [[0.52372944]],

         [[0.5088606 ]],

         [[0.8803636 ]],

         [[0.11377084]],

         [[0.6813196 ]],

         [[0.54288495]],

         [[0.04928088]],

         [[0.68769765]],

         [[0.31924403]],

         [[0.47953212]],

         [[0.22639894]],

         [[0.34083533]],

         [[0.36209035]],

         [[0.96956146]],

         [[0.6346265 ]],

         [[0.17654824]],

         [[0.35434842]],

         [[0.7780837 ]],

         [[0.4478408 ]],

      

In [184]:
tf.squeeze(matrix_squez, axis=[3,4, 5])

<tf.Tensor: shape=(1, 1, 50), dtype=float32, numpy=
array([[[0.71128917, 0.77877116, 0.36490285, 0.9530003 , 0.49915147,
         0.31188822, 0.39449155, 0.5906935 , 0.13221145, 0.37026978,
         0.5638151 , 0.9600681 , 0.38443553, 0.22657108, 0.7337091 ,
         0.18864179, 0.2322309 , 0.52372944, 0.5088606 , 0.8803636 ,
         0.11377084, 0.6813196 , 0.54288495, 0.04928088, 0.68769765,
         0.31924403, 0.47953212, 0.22639894, 0.34083533, 0.36209035,
         0.96956146, 0.6346265 , 0.17654824, 0.35434842, 0.7780837 ,
         0.4478408 , 0.43103004, 0.73788166, 0.37174475, 0.71096385,
         0.91982245, 0.8890587 , 0.51341915, 0.51375294, 0.6079956 ,
         0.53363097, 0.30792522, 0.72625375, 0.4965216 , 0.9710821 ]]],
      dtype=float32)>

##### One-hot encoding

In [185]:
color_list = [0, 1, 2, 3] # Colors red, green, blue, yellow
tf.one_hot(color_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [186]:
tf.one_hot(color_list, depth=4, on_value='Y', off_value='N')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'Y']], dtype=object)>

##### Math Operations

In [187]:
my_list = tf.range(1, 10)
my_list

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [188]:
tf.square(my_list)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [191]:
tf.sqrt(tf.cast(my_list, dtype=tf.float32 ))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [192]:
tf.constant(np.arange(1, 5)).numpy()

array([1, 2, 3, 4])

In [194]:
!nvidia-smi

Tue Dec 28 18:42:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.35       Driver Version: 471.35       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   54C    P0    22W /  N/A |   4856MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------